### ISSUE TITLE
我在加载数据集的时候一直报错，找不到文件，我的qvhighlight数据集就放在根目录下，运行inference.sh一直跑不通，可以帮我看一下是哪里需要调整嘛

### ISSUE THREAD

**Issue by XiaoLei2123** [mingyao1120/TR-DETR#5]
Traceback (most recent call last):
  File "tr_detr/inference.py", line 423, in <module>
    start_inference(split=split, splitfile=splitfile)
  File "tr_detr/inference.py", line 413, in start_inference
    eval_epoch(model, eval_dataset, opt, save_submission_filename, criterion=criterion)
  File "tr_detr/inference.py", line 299, in eval_epoch
    submission, eval_loss_meters = get_eval_res(model, eval_loader, opt, epoch_i, criterion, tb_writer)
  File "tr_detr/inference.py", line 254, in get_eval_res
    eval_res, eval_loss_meters = compute_mr_results(model, eval_loader, opt, epoch_i, criterion, tb_writer)  # list(dict)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "tr_detr/inference.py", line 185, in compute_mr_results
    for batch in tqdm(eval_loader, desc="compute st ed scores"):
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/autodl-tmp/TR-DETR/tr_detr/start_end_dataset.py", line 90, in __getitem__
    model_inputs["query_feat"] = self._get_query_feat_by_qid(meta["qid"])  # (Dq, ) or (Lq, Dq)
  File "/root/autodl-tmp/TR-DETR/tr_detr/start_end_dataset.py", line 324, in _get_query_feat_by_qid
    q_feat = np.load(q_feat_path)[self.q_feat_type].astype(np.float32)
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '.../qid2579.npz'

**Comment by Lonicer** [comment]
> Traceback (most recent call last): File "tr_detr/inference.py", line 423, in start_inference(split=split, splitfile=splitfile) File "tr_detr/inference.py", line 413, in start_inference eval_epoch(model, eval_dataset, opt, save_submission_filename, criterion=criterion) File "tr_detr/inference.py", line 299, in eval_epoch submission, eval_loss_meters = get_eval_res(model, eval_loader, opt, epoch_i, criterion, tb_writer) File "tr_detr/inference.py", line 254, in get_eval_res eval_res, eval_loss_meters = compute_mr_results(model, eval_loader, opt, epoch_i, criterion, tb_writer) # list(dict) File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context return func(*args, **kwargs) File "tr_detr/inference.py", line 185, in compute_mr_results for batch in tqdm(eval_loader, desc="compute st ed scores"): File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1185, in **iter** for obj in iterable: File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in **next** data = self._next_data() File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data return self._process_data(data) File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data data.reraise() File "/root/miniconda3/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise raise self.exc_type(msg) FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0. Original Traceback (most recent call last): File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop data = fetcher.fetch(index) File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/autodl-tmp/TR-DETR/tr_detr/start_end_dataset.py", line 90, in **getitem** model_inputs["query_feat"] = self._get_query_feat_by_qid(meta["qid"]) # (Dq, ) or (Lq, Dq) File "/root/autodl-tmp/TR-DETR/tr_detr/start_end_dataset.py", line 324, in _get_query_feat_by_qid q_feat = np.load(q_feat_path)[self.q_feat_type].astype(np.float32) File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load fid = stack.enter_context(open(os_fspath(file), "rb")) FileNotFoundError: [Errno 2] No such file or directory: '.../qid2579.npz'

您好，可以先查找一下对应目录下有无需要读入的文件，若没有，则数据集需要重新从所给目录下载并解压到对应目录（实践发现，moment-detr提出的特征和后续工作的特征好像存在差异），希望您早日解决~
